### ISSUE TITLE
Use json-stable-stringify for stringifying

### ISSUE THREAD

**Issue by djmitche** [jhford/postgres-entities#1]
```js
id = Buffer.from(JSON.stringify({taskId: 'abcdef1234'})).toString('base64');
```

For a multi-value key, the property order is not stable, and might end up creating several different id's.  [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) can avoid this risk.

**Comment by jhford** [comment]
I think based on the changes to the id creation, that this issue is no longer present.
